let nombre1 = prompt('Ingrese su nombre:')
let nombre2 = prompt('Ingrese su nombre:')
let nombre3 = prompt('Ingrese su nombre:')
let nombre4 = prompt('Ingrese su nombre:')
let nombre5 = prompt('Ingrese su nombre:')